name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Home
        run: curl -s https://movie-api-c0f7.onrender.com/

      - name: Health
        run: curl -s https://movie-api-c0f7.onrender.com/health

      - name: Recommend test
        run: curl -s "https://movie-api-c0f7.onrender.com/recommend?movie=avatar&n=5"
